name: Deploy

on:
  push:
    branches:
      - dev/client

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOMAIN }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /home/elice/MealAi-Client
          git pull origin dev/client
          npm install
          npm run build
          sudo systemctl reload nginx
